services:
  profiles:
    build:
      context: ./profiles
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  about:
    build:
      context: ./about
    ports:
      - "3002:3002"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    depends_on:
      - profiles
      - about
    container_name: server_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
