events {}

http {
    upstream profiles {
        server profiles:3001;
        
    }

    upstream about {
        server about:3002;
    }

    server {
        listen 80;
        
        location /profiles/ {
            proxy_pass http://profiles/;
        }

        location /about/ {
            proxy_pass http://about/;
        }
    }
}